// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ligacao-politica/usecase/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/ligacao-politica/usecase/interface.go -destination=internal/ligacao-politica/usecase/mock.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAnalisarLigacaoPoliticaUseCaseInterface is a mock of AnalisarLigacaoPoliticaUseCaseInterface interface.
type MockAnalisarLigacaoPoliticaUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder is the mock recorder for MockAnalisarLigacaoPoliticaUseCaseInterface.
type MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder struct {
	mock *MockAnalisarLigacaoPoliticaUseCaseInterface
}

// NewMockAnalisarLigacaoPoliticaUseCaseInterface creates a new mock instance.
func NewMockAnalisarLigacaoPoliticaUseCaseInterface(ctrl *gomock.Controller) *MockAnalisarLigacaoPoliticaUseCaseInterface {
	mock := &MockAnalisarLigacaoPoliticaUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalisarLigacaoPoliticaUseCaseInterface) EXPECT() *MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Executar mocks base method.
func (m *MockAnalisarLigacaoPoliticaUseCaseInterface) Executar(ctx context.Context, licitacoes []AnalisarLigacaoPoliticaRequest) (*AnalisarLigacaoPoliticaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Executar", ctx, licitacoes)
	ret0, _ := ret[0].(*AnalisarLigacaoPoliticaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Executar indicates an expected call of Executar.
func (mr *MockAnalisarLigacaoPoliticaUseCaseInterfaceMockRecorder) Executar(ctx, licitacoes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Executar", reflect.TypeOf((*MockAnalisarLigacaoPoliticaUseCaseInterface)(nil).Executar), ctx, licitacoes)
}
