// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/clients/opencnpj/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/shared/clients/opencnpj/interface.go -destination=internal/shared/clients/opencnpj/mock.go -package=opencnpj
//

// Package opencnpj is a generated GoMock package.
package opencnpj

import (
	context "context"
	reflect "reflect"

	types "github.com/danyele/podp/internal/shared/types"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Buscar mocks base method.
func (m *MockClient) Buscar(ctx context.Context, cnpj string) (*types.OpenCNPJResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Buscar", ctx, cnpj)
	ret0, _ := ret[0].(*types.OpenCNPJResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Buscar indicates an expected call of Buscar.
func (mr *MockClientMockRecorder) Buscar(ctx, cnpj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Buscar", reflect.TypeOf((*MockClient)(nil).Buscar), ctx, cnpj)
}
