// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/clients/tcu/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/shared/clients/tcu/interface.go -destination=internal/shared/clients/tcu/mock.go -package=tcu
//

// Package tcu is a generated GoMock package.
package tcu

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BuscarContasIrregulares mocks base method.
func (m *MockClient) BuscarContasIrregulares(ctx context.Context, filter TCUQueryParams) ([]ContasIrregulares, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarContasIrregulares", ctx, filter)
	ret0, _ := ret[0].([]ContasIrregulares)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarContasIrregulares indicates an expected call of BuscarContasIrregulares.
func (mr *MockClientMockRecorder) BuscarContasIrregulares(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarContasIrregulares", reflect.TypeOf((*MockClient)(nil).BuscarContasIrregulares), ctx, filter)
}

// BuscarFinsEleitorais mocks base method.
func (m *MockClient) BuscarFinsEleitorais(ctx context.Context, filter TCUQueryParams) ([]FinsEleitorais, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarFinsEleitorais", ctx, filter)
	ret0, _ := ret[0].([]FinsEleitorais)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarFinsEleitorais indicates an expected call of BuscarFinsEleitorais.
func (mr *MockClientMockRecorder) BuscarFinsEleitorais(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarFinsEleitorais", reflect.TypeOf((*MockClient)(nil).BuscarFinsEleitorais), ctx, filter)
}

// BuscarInabilitados mocks base method.
func (m *MockClient) BuscarInabilitados(ctx context.Context, filter TCUQueryParams) ([]Sancoes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInabilitados", ctx, filter)
	ret0, _ := ret[0].([]Sancoes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInabilitados indicates an expected call of BuscarInabilitados.
func (mr *MockClientMockRecorder) BuscarInabilitados(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInabilitados", reflect.TypeOf((*MockClient)(nil).BuscarInabilitados), ctx, filter)
}

// BuscarInidoneos mocks base method.
func (m *MockClient) BuscarInidoneos(ctx context.Context, filter TCUQueryParams) ([]Sancoes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInidoneos", ctx, filter)
	ret0, _ := ret[0].([]Sancoes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInidoneos indicates an expected call of BuscarInidoneos.
func (mr *MockClientMockRecorder) BuscarInidoneos(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInidoneos", reflect.TypeOf((*MockClient)(nil).BuscarInidoneos), ctx, filter)
}
